version: '2.4'

services:
  mongo:
    image: "bitnami/mongodb:latest"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 60s

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/cognitev
      - PORT=3000
    volumes:
      - .:/app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3000:3000


